# Generated by Django 4.1.6 on 2023-02-07 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garden_calendar", "0003_rename_plants_plant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plant",
            name="time_modified",
        ),
    ]
