# Generated by Django 4.1.6 on 2023-02-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_calendar", "0004_remove_plant_time_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="todos",
            field=models.CharField(default="", max_length=110),
        ),
    ]
