# Generated by Django 4.1.6 on 2023-02-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_calendar", "0005_plant_todos"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="selected_plants",
            field=models.ManyToManyField(to="garden_calendar.plant"),
        ),
        migrations.DeleteModel(
            name="SelectedPlant",
        ),
    ]
