# Generated by Django 4.1.6 on 2023-02-14 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garden_calendar", "0007_user_language_delete_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="language",
        ),
        migrations.RemoveField(
            model_name="user",
            name="selected_plants",
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("si", "Slovenian")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("selected_plants", models.ManyToManyField(to="garden_calendar.plant")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
