# Generated by Django 4.1.6 on 2023-02-14 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("garden_calendar", "0009_rename_settings_setting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="selected_plants",
        ),
        migrations.CreateModel(
            name="SelectedPlant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("selected_plants", models.ManyToManyField(to="garden_calendar.plant")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
