# Generated by Django 4.1.6 on 2023-02-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_calendar", "0010_remove_setting_selected_plants_selectedplant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="setting",
            name="user",
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("si", "Slovenian")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="selected_plants",
            field=models.ManyToManyField(to="garden_calendar.plant"),
        ),
        migrations.DeleteModel(
            name="SelectedPlant",
        ),
        migrations.DeleteModel(
            name="Setting",
        ),
    ]
