# Generated by Django 4.1.6 on 2023-02-14 12:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("garden_calendar", "0012_addemail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="addemail",
            old_name="mail",
            new_name="email",
        ),
    ]
