# Generated by Django 4.1.6 on 2023-02-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garden_calendar", "0013_rename_mail_addemail_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications",
            field=models.CharField(default="", max_length=27),
        ),
    ]
